#controllers:
#    resource:
#        path: ../src/Controller/
#        namespace: App\Controller
#    type: attribute

panel_main_index:
    path: /
    controller: App\Controller\PanelMainController::index
test_route:
    path: /{param}
    controller: App\Controller\PanelMainController::test
    defaults:
        param: 662
#    requirements:
#        param: '\d+'